//Model
let currentIndexOfMainCarousel = 0;

const model = {
    app: {
        loggedInUser: null,
        currentPage: 'loginPage',
        displayMode: 'dark',
        language: 'no',
        logo: './img/turtlePowerLogo',
    },
    inputs: {
        user: {
            username: '',
            password: '',
            email: '',
            profileImage: '',
            isAdmin: false,
            description: '',
            favoriteMovies: [],
        },
    },
    //Data
    users:[
        // user for easy access:
        {
            username: '',
            password: '',
            email: '',
            profileImage: './img/profileImages/emptyUser.jpg',
            isAdmin: false,
            description: '',
            favoriteMovies: [],
        },
        {
            username: 'Ellie',
            password: '1234',
            email: 'elliemarie@getacademy.no',
            profileImage: './img/profileImages/EllieMarie.jpg',
            isAdmin: true,
            description: "Hello, my name is Ellie, and I'm the developer of this website. I'm writing everthing myself and this is only for training purpuses, but it is a really fun project to work on.",
            favoriteMovies: [
                {
                    id: 1,
                    title: 'The Dukes of hazzard',
                    releaseDate: '2005',
                    cover: 'dukesOfHazzard.jpg',
                    duration: '1h and 44m',
                    description: "Cousins Bo, Luke, and Daisy Duke, and their uncle Jesse, egg on the authorities of Hazzard County, Boss Hogg and Sheriff Coltrane",
                    overallRating: '510',
                    personalRating: '880',
                    genre: ['Comedy'],
                    directors: ['Jay Chandrasekhar'],
                    staringActors: ['Seann William Scott', 'Johnny Knoxville', 'Jessica Simpson'],
                },
            ],
        },
        {
            username: 'Admin',
            password: '1234',
            email: 'elliemarie@getacademy.no',
            profileImage: '',
            isAdmin: true,
            description: "Im the Admin here",
            favoriteMovies: [],
        },
    ],
    
    movies:[
        {
            id: 1,
            title: 'The Dukes of hazzard',
            releaseDate: '2005',
            cover: 'dukesOfHazzard.jpg',
            duration: '1h and 44m',
            description: "Cousins Bo, Luke, and Daisy Duke, and their uncle Jesse, egg on the authorities of Hazzard County, Boss Hogg and Sheriff Coltrane",
            overallRating: '510',
            personalRating: 'You have not rated this movie yet',
            genre: ['Comedy'],
            directors: ['Jay Chandrasekhar'],
            staringActors: ['Seann William Scott', 'Johnny Knoxville', 'Jessica Simpson'],
        },
        {
            id: 2,
            title: 'The Grudge (2004)',
            releaseDate: '2004',
            cover: 'theGrudge.jpg',
            duration: '1h and 31m',
            description: "An American nurse living and working in Tokyo is exposed to a mysterious supernatural curse, one that locks a person in a powerful rage before claiming their life and spreading to another victim.",
            overallRating: '590',
            personalRating: 'You have not rated this movie yet',
            genre: ['Horror', 'Mystery', 'Thriller'],
            directors: ['Takashi Shimizu'],
            staringActors: ['Sarah Michelle Gellar', 'Jason Behr', 'Clea DuVall'],
        },
        {
            id: 3,
            title: 'Titanic',
            releaseDate: '1997',
            cover: 'titanic.jpg',
            duration: '3h and 14m',
            description: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
            overallRating: '790',
            personalRating: 'You have not rated this movie yet',
            genre: ['Drama', 'Romance'],
            directors: ['James Cameron'],
            staringActors: ['Leonardo DiCaprio', 'Kate Winslet', 'Billy Zane'],
        },
        {
            id: 4,
            title: 'Eerie',
            releaseDate: '2018',
            cover: 'eerie.jpg',
            duration: '1h and 41m',
            description: "When a student's suicide rattles an all-girls Catholic school, a clairvoyant guidance counselor leans on a ghost to uncover the convent's abusive past.",
            overallRating: '470',
            personalRating: 'You have not rated this movie yet',
            genre: ['Horror', 'Mystery', 'Thriller'],
            directors: ['Mikhal Red'],
            staringActors: ['Bea Alonzo', 'Charo Santos-Concie', 'Jake Cuenca'],
        },
        {
            id: 5,
            title: 'Shrek',
            releaseDate: '2001',
            cover: 'shrek.jpg',
            duration: '1h and 30m',
            description: "A mean lord exiles fairytale creatures to the swamp of a grumpy ogre, who must go on a quest and rescue a princess for the lord in order to get his land back.",
            overallRating: '790',
            personalRating: 'You have not rated this movie yet',
            genre: ['Animation', 'Adventure', 'Comedy'],
            directors: ['Andrew Adamson', 'Vicky Jenson'],
            staringActors: ['Mike Myers', 'Eddie Murphy', 'Cameron Diaz'],
        },
        {
            id: 6,
            title: 'The Lion King',
            releaseDate: '1994',
            cover: 'theLionKing.jpg',
            duration: '1h and 28m',
            description: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
            overallRating: '850',
            personalRating: 'You have not rated this movie yet',
            genre: ['Animation', 'Adventure', 'Drama'],
            directors: ['Roger Allers', 'Rob Minkoff'],
            staringActors: ['Matthew Broderick', 'Jeremy Irons', 'James Earl Jones'],
        },
        {
            id: 7,
            title: 'Inside Out',
            releaseDate: '2015',
            cover: 'insideOut.jpg',
            duration: '1h and 35m',
            description: "After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust, and Sadness - conflict on how best to navigate a new city, house, and school.",
            overallRating: '810',
            personalRating: 'You have not rated this movie yet',
            genre: ['Animation','Adventure', 'Comedy'],
            directors: ['Pete Docter', 'Ronnie Del Carmen'],
            staringActors: ['Amy Poehler', 'Bill Hader', 'Lewis Black'],
        },
        {
            id: 8,
            title: 'The Godfather',
            releaseDate: '1972',
            cover: 'theGodfather.jpg',
            duration: '2h and 55m',
            description: "Don Vito Corleone, head of a mafia family, decides to hand over his empire to his youngest son Michael. However, his decision unintentionally puts the lives of his loved ones in grave danger.",
            overallRating: '920',
            personalRating: 'You have not rated this movie yet',
            genre: ['Crime', 'Drama'],
            directors: ['Francis Ford Coppola'],
            staringActors: ['Marlon Brando', 'Al Pacino', 'James Caan'],
        },
        {
            id: 9,
            title: 'Jurassic Park',
            releaseDate: '1993',
            cover: 'jurassicPark.jpg',
            duration: '2h and 7m',
            description: "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
            overallRating: '820',
            personalRating: 'You have not rated this movie yet',
            genre: ['Action', 'Adventure', 'Sci-Fi'],
            directors: ['Steven SpielBerg'],
            staringActors: ['Sam Niell', 'Laura Dern', 'Jeff Goldblum'],
        },
        {
            id: 10,
            title: 'Monty Python`s Life of Brian',
            releaseDate: '1979',
            cover: 'lifeOfBrian.jpg',
            duration: '1h and 34m',
            description: "Born on the original Christmas in the stable next door to Jesus Christ, Brian of Nazareth spends his life being mistaken for a messiah.",
            overallRating: '800',
            personalRating: 'You have not rated this movie yet',
            genre: ['Comedy'],
            directors: ['Terry Jones'],
            staringActors: ['Grahm Chapman', 'John Cleese', 'Michael Palin'],
        },
        {
            id: 11,
            title: 'The Lord of the Rings: The Fellowship of the Ring',
            releaseDate: '2001',
            cover: 'lordOfTheRings.jpg',
            duration: '2h and 58m',
            description: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
            overallRating: '880',
            personalRating: 'You have not rated this movie yet',
            genre: ['Action', 'Adventure', 'Drama'],
            directors: ['Peter Jackson'],
            staringActors: ['Elijah Wood', 'Ian McKellen', 'Orlando Bloom'],
        },
        {
            id: 12,
            title: 'Pulp Fiction',
            releaseDate: '1994',
            cover: 'pulpFiction.jpg',
            duration: '2h and 34m',
            description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
            overallRating: '890',
            personalRating: 'You have not rated this movie yet',
            genre: ['Crime', 'Drama'],
            directors: ['Quentin Tarantino'],
            staringActors: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
        },
        {
            id: 13,
            title: 'Fight Club',
            releaseDate: '1999',
            cover: 'fightClub.jpg',
            duration: '2h and 19m',
            description: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
            overallRating: '880',
            personalRating: 'You have not rated this movie yet',
            genre: ['Drama'],
            directors: ['David Fincher'],
            staringActors: ['Brad Pitt', 'Edward Norton', 'Meat Loaf'],
        },
        {
            id: 14,
            title: 'Forrest Gump',
            releaseDate: '1994',
            cover: 'forrestGump.jpg',
            duration: '2h and 22m',
            description: "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
            overallRating: '882',
            personalRating: 'You have not rated this movie yet',
            genre: ['Drama', 'Romance'],
            directors: ['Robert Zemeckis'],
            staringActors: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
        },
        {
            id: 15,
            title: 'Se7en',
            releaseDate: '1995',
            cover: 'se7en.jpg',
            duration: '2h and 7m',
            description: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
            overallRating: '860',
            personalRating: 'You have not rated this movie yet',
            genre: ['Crime', 'Drama', 'Mystery'],
            directors: ['David Fincher'],
            staringActors: ['Morgan Freeman', 'Brad Pitt', 'Kevin Spacey'],
        },
        {
            id: 16,
            title: 'The Silence of the Lambs',
            releaseDate: '1991',
            cover: 'theSilenceOfTheLambs.jpg',
            duration: '1h and 58m',
            description: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
            overallRating: '867',
            personalRating: 'You have not rated this movie yet',
            genre: ['Crime', 'Drama', 'Thriller'],
            directors: ['Jonathan Demme'],
            staringActors: ['Thomas Harris', 'Ted Tally'],
        },
        {
            id: 17,
            title: 'Interstellar',
            releaseDate: '2014',
            cover: 'interstellar.jpg',
            duration: '2h and 49m',
            description: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
            overallRating: '870',
            personalRating: 'You have not rated this movie yet',
            genre: ['Adventure', 'Drama', 'Sci-Fi'],
            directors: ['Christopher Nolan'],
            staringActors: ['Matthew McConaghey','Anne Hathaway', 'Jessica Chastain'],
        },
        {
            id: 18,
            title: 'The Green Mile',
            releaseDate: '1999',
            cover: 'theGreenMile.jpg',
            duration: '3h and 9m',
            description: "A tale set on death row in a Southern jail, where gentle giant John possesses the mysterious power to heal people's ailments. When the lead guard, Paul, recognizes John's gift, he tries to help stave off the condemned man's execution.",
            overallRating: '865',
            personalRating: 'You have not rated this movie yet',
            genre: ['Crime', 'Drama', 'Fantasy'],
            directors: ['Frank Darabont'],
            staringActors: ['Tom Hanks', 'Michael Clarke Ducan', 'David Morse'],
        },
        {
            id: 19,
            title: 'Back To The Future',
            releaseDate: '1985',
            cover: 'backToTheFuture.jpg',
            duration: '1h and 56m',
            description: "Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.",
            overallRating: '852',
            personalRating: 'You have not rated this movie yet',
            genre: ['Adventure', 'Comedy', 'Sci-Fi'],
            directors: ['Robert Zemeckis'],
            staringActors: ['Michael J. Fox', 'Christopher Lloyd', 'Lea Thompson'],
        },
        {
            id: 20,
            title: 'The Pianist',
            releaseDate: '2002',
            cover: 'thePianist.jpg',
            duration: '2h and 30m',
            description: "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.",
            overallRating: '854',
            personalRating: 'You have not rated this movie yet',
            genre: ['Biography', 'Drama', 'Music'],
            directors: ['Roman Polanski'],
            staringActors: ['Ardien Brodly', 'Thomas Kretschmann', 'Frank Finlay'],
        },
        {
            id: 21,
            title: 'The Shawshank Redemption',
            releaseDate: '1994',
            cover: 'theShawshankRedemption.jpg',
            duration: '2h and 22m',
            description: "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.",
            overallRating: '933',
            personalRating: 'You have not rated this movie yet',
            genre: ['Drama'],
            directors: ['Frank Darabont'],
            staringActors: ['Tim Robbins', 'Morgan Freeman','Bob Gunton'],
        },
        {
            id: 22,
            title: 'The Dark Knight',
            releaseDate: '2008',
            cover: 'theDarkKnight.jpg',
            duration: '2h and 32m',
            description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
            overallRating: '909',
            personalRating: 'You have not rated this movie yet',
            genre: ['Action', 'Crime', 'Drama'],
            directors: ['Christopher Nolan'],
            staringActors: ['Christian Bale','Heath Ledger', 'Aaron Eckhart'],
        },
        {
            id: 23,
            title: 'The Godfather Part II',
            releaseDate: '1974',
            cover: 'theGodfatherPartII.jpg',
            duration: '3h and 22m',
            description: "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
            overallRating: '908',
            personalRating: 'You have not rated this movie yet',
            genre: ['Crime', 'Drama'],
            directors: ['Francis Ford Coppola'],
            staringActors: ['Al Pacino', 'Robert De Niro', 'Robert Duvall'],
        },
        {
            id: 24,
            title: '12 Angry Men',
            releaseDate: '1957',
            cover: '12AngryMen.jpg',
            duration: '1h and 36m',
            description: "The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.",
            overallRating: '907',
            personalRating: 'You have not rated this movie yet',
            genre: ['Crime', 'Drama'],
            directors: ['Sidney Lumet'],
            staringActors: ['StarsHenry Fonda', 'Lee J. Cobb', 'Martin Balsam'],
        },
        {
            id: 25,
            title: 'Schindler`s List',
            releaseDate: '1993',
            cover: 'schindlersList.jpg',
            duration: '3h and 15m',
            description: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
            overallRating: '906',
            personalRating: 'You have not rated this movie yet',
            genre: ['Biography'],
            directors: ['Steven Spielberg'],
            staringActors: ['Liam Neeson', 'Ralph Fiennes', 'Ben Kingsley'],
        },
        {
            id: 26,
            title: 'The Lord of the Rings: The Return of the King',
            releaseDate: '2003',
            cover: 'theLordoftheRingsTheReturnoftheKing.jpg',
            duration: '3h and 21m',
            description: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
            overallRating: '905',
            personalRating: 'You have not rated this movie yet',
            genre: ['Action', 'Adventure', 'Drama'],
            directors: ['Peter Jackson'],
            staringActors: ['Elijah Wood', 'Viggo Mortensen', 'Ian McKellen'],
        },
        {
            id: 27,
            title: 'The Good, The Bad And The Ugly',
            releaseDate: '1966',
            cover: 'theGoodThe BadAndTheUgly.jpg',
            duration: "2h and 41m",
            description: "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
            overallRating: '885',
            personalRating: 'You have not rated this movie yet',
            genre: ['Adventure', 'Western'],
            directors: ['Sergio Leone'],
            staringActors: ['Clint Eastwood', 'Eli Wallach', 'Lee Van Cleef'],
        },
        {
            id: 28,
            title: 'The Lord of the Rings: The Two Towers',
            releaseDate: '2002',
            cover: 'theLordoftheRingsThe TwoTowers.jpg',
            duration: '2h and 59m',
            description: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.",
            overallRating: '884',
            personalRating: 'You have not rated this movie yet',
            genre: ['Action', 'Adventure', 'Drama'],
            directors: ['Peter Jackson'],
            staringActors: ['Elijah Wood', 'Ian McKellen', 'Viggo Mortensen'],
        },
        {
            id: 29,
            title: 'Inception',
            releaseDate: '2010',
            cover: 'inception.jpg',
            duration: '2h and 28m',
            description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
            overallRating: '889',
            personalRating: 'You have not rated this movie yet',
            genre: ['Action', 'Adventure', 'Sci-Fi'],
            directors: ['Christopher Nolan'],
            staringActors: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
        },
        {
            id: 30,
            title: 'Star Wars: Episode V - The Empire Strikes Back',
            releaseDate: '1980',
            cover: 'StarWarsEpisode_V_TheEmpireStrikesBack.jpg',
            duration: '2h and 4m',
            description: "After the Rebels are overpowered by the Empire, Luke Skywalker begins his Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.",
            overallRating: '879',
            personalRating: 'You have not rated this movie yet',
            genre: ['Action', 'Adventure', 'Fantasy'],
            directors: ['Irvin Kershner'],
            staringActors: ['Mark Hamill', 'Harrison Ford', 'Carrie Fisher'],
        },
        {
            id: 31,
            title: 'The Matrix',
            releaseDate: '1999',
            cover: 'theMatrix.jpg',
            duration: '2h and 16m',
            description: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
            overallRating: '872',
            personalRating: 'You have not rated this movie yet',
            genre: ['Action', 'Sci-Fi'],
            directors: ['Lana Wachowski', 'Lilly Wachowski'],
            staringActors: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
        },
        {
            id: 32,
            title: 'Goodfellas',
            releaseDate: '1990',
            cover: 'goodfellas.jpg',
            duration: '2h and 25',
            description: "The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen and his mob partners Jimmy Conway and Tommy DeVito.",
            overallRating: '877',
            personalRating: 'You have not rated this movie yet',
            genre: ['Biography', 'Crime', 'Drama'],
            directors: ['Martin Scorsese'],
            staringActors: ['Robert De Niro', 'Ray Liotta', 'Joe Pesci'],
        },
        {
            id: 33,
            title: 'One Flew Over the Cuckoo`s Nest',
            releaseDate: '1975',
            cover: 'oneFlewOvertheCuckoosNest.jpg',
            duration: '2h and 13m',
            description: "In the Fall of 1963, a Korean War veteran and criminal pleads insanity and is admitted to a mental institution, where he rallies up the scared patients against the tyrannical nurse.",
            overallRating: '878',
            personalRating: 'You have not rated this movie yet',
            genre: ['Drama'],
            directors: ['Milos Forman'],
            staringActors: ['Jack Nicholson', 'Louise Fletcher', 'Michael Berryman'],
        },
        {
            id: 34,
            title: ' It`s a Wonderful Life',
            releaseDate: '1946',
            cover: 'itsaWonderfulLife.jpg',
            duration: '1946',
            description: "An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.",
            overallRating: '869',
            personalRating: 'You have not rated this movie yet',
            genre: ['Drama', 'Family', 'Fantasy'],
            directors: ['Frank Capra'],
            staringActors: ['James Stewart', 'Donna Reed', 'Lionel Barrymore'],
        },
        {
            id: 35,
            title: 'Spider-Man: Across the Spider-Verse',
            releaseDate: '2023',
            cover: 'spiderManAcrosstheSpiderVerse.jpg',
            duration: '2h and 20m',
            description: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a hero.",
            overallRating: '878',
            personalRating: 'You have not rated this movie yet',
            genre: ['Joaquim Dos Santos', 'Kemp Powers', 'Justin K. Thompson'],
            directors: [],
            staringActors: ['Shameik Moore', 'Hailee Steinfeld', 'Brian Tyree Henry'],
        },
        {
            id: 36,
            title: 'Seven Samurai',
            releaseDate: '1954',
            cover: 'sevenSamurai.jpg',
            duration: '3h and 27m',
            description: "Farmers from a village exploited by bandits hire a veteran samurai for protection, who gathers six other samurai to join him.",
            overallRating: '866',
            personalRating: 'You have not rated this movie yet',
            genre: ['Action', 'Drama'],
            directors: ['Akira Kurosawa'],
            staringActors: ['Toshirô Mifune', 'Takashi Shimura', 'Keiko Tsushima'],
        },
        {
            id: 37,
            title: 'Saving Private Ryan',
            releaseDate: '1998',
            cover: 'savingPrivateRyan.jpg',
            duration: '2h and 49m',
            description: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
            overallRating: '864',
            personalRating: 'You have not rated this movie yet',
            genre: ['Drama', 'War'],
            directors: ['Steven Spielberg'],
            staringActors: ['Tom Hanks', 'Matt Damon', 'Tom Sizemore'],
        },
        {
            id: 38,
            title: 'City of God ',
            releaseDate: '2002',
            cover: 'cityOfCod.jpg',
            duration: '2h and 10m',
            description: "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.",
            overallRating: '865',
            personalRating: 'You have not rated this movie yet',
            genre: ['Crime', 'Drama'],
            directors: ['Fernando Meirelles', 'Kátia Lund'],
            staringActors: ['Alexandre Rodrigues', 'Leandro Firmino', 'Matheus Nachtergaele'],
        },
        {
            id: 39,
            title: 'Life is Beautiful',
            releaseDate: '1997',
            cover: 'lifeisBeautiful.jpg',
            duration: '1h and 56m',
            description: "When an open-minded Jewish waiter and his son become victims of the Holocaust, he uses a perfect mixture of will, humor and imagination to protect his son from the dangers around their camp",
            overallRating: '864',
            personalRating: 'You have not rated this movie yet',
            genre: ['Comedy', 'Drama', 'Romance'],
            directors: ['Roberto Benigni'],
            staringActors: ['Roberto Benigni', 'Nicoletta Braschi', 'Giorgio Cantarini'],
        },
        {
            id: 40,
            title: ' Star Wars',
            releaseDate: '1977',
            cover: 'starWars.jpg',
            duration: '2h and 1m',
            description: "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.",
            overallRating: '863',
            personalRating: 'You have not rated this movie yet',
            genre: ['Action', 'Adventure', 'Fantasy'],
            directors: ['George Lucas'],
            staringActors: ['Mark Hamhill', 'Harrison Ford', 'Carrie Fisher'],
        },
        {
            id: 41,
            title: 'Terminator 2: Judgment Day',
            releaseDate: '1991',
            cover: 'terminator2JudgmentDay.jpg',
            duration: '2h and 17m',
            description: "A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her ten year old son John from an even more advanced and powerful cyborg.",
            overallRating: '862',
            personalRating: 'You have not rated this movie yet',
            genre: ['Action', 'Sci-Fi'],
            directors: ['Jamens Cameron'],
            staringActors: ['Arnold Schwarzenegger', 'Linda Hamilton', 'Edward Furlong'],
        },
        {
            id: 42,
            title: 'Spirited Away',
            releaseDate: '2001',
            cover: 'spiritedAway.jpg',
            duration: '2h and 5m',
            description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, a world where humans are changed into beasts.",
            overallRating: '861',
            personalRating: 'You have not rated this movie yet',
            genre: ['Animation', 'Adventure', 'Family'],
            directors: ['Hayao Miyazaki'],
            staringActors: ['Daveigh Chase', 'Suzanne Pleshette', 'Miyu Irino'],
        },
        {
            id: 43,
            title: 'Psycho',
            releaseDate: '1960',
            cover: 'psycho.jpg',
            duration: '1h and 49m',
            description: "A Phoenix secretary embezzles $40,000 from her employer's client, goes on the run and checks into a remote motel run by a young man under the domination of his mother.",
            overallRating: '859',
            personalRating: 'You have not rated this movie yet',
            genre: ['Horror', 'Mystery', 'Thriller'],
            directors: ['Alfred Hitchcock'],
            staringActors: ['Anthony Perkins', 'Janet Leigh', 'Vera Miles'],
        },
        //////////////////////////////////////////////////////////////////////////////////////////////
        // Stopped at Psycho at place 34, the next to add wil be 'Parasite'.
        //////////////////////////////////////////////////////////////////////////////////////////////
        // {
        //     id: 44,
        //     title: '',
        //     releaseDate: '',
        //     cover: '',
        //     duration: '',
        //     description: "",
        //     overallRating: '',
        //     personalRating: 'You have not rated this movie yet',
        //     genre: [],
        //     directors: [],
        //     staringActors: [],
        // },
        // {
        //     id: 45,
        //     title: '',
        //     releaseDate: '',
        //     cover: '',
        //     duration: '',
        //     description: "",
        //     overallRating: '',
        //     personalRating: 'You have not rated this movie yet',
        //     genre: [],
        //     directors: [],
        //     staringActors: [],
        // },
        // {
        //     id: 46,
        //     title: '',
        //     releaseDate: '',
        //     cover: '',
        //     duration: '',
        //     description: "",
        //     overallRating: '',
        //     personalRating: 'You have not rated this movie yet',
        //     genre: [],
        //     directors: [],
        //     staringActors: [],
        // },
        // {
        //     id: 47,
        //     title: '',
        //     releaseDate: '',
        //     cover: '',
        //     duration: '',
        //     description: "",
        //     overallRating: '',
        //     personalRating: 'You have not rated this movie yet',
        //     genre: [],
        //     directors: [],
        //     staringActors: [],
        // },
        // {
        //     id: 48,
        //     title: '',
        //     releaseDate: '',
        //     cover: '',
        //     duration: '',
        //     description: "",
        //     overallRating: '',
        //     personalRating: 'You have not rated this movie yet',
        //     genre: [],
        //     directors: [],
        //     staringActors: [],
        // },
        // {
        //     id: 49,
        //     title: '',
        //     releaseDate: '',
        //     cover: '',
        //     duration: '',
        //     description: "",
        //     overallRating: '',
        //     personalRating: 'You have not rated this movie yet',
        //     genre: [],
        //     directors: [],
        //     staringActors: [],
        // },
        // {
        //     id: 50,
        //     title: '',
        //     releaseDate: '',
        //     cover: '',
        //     duration: '',
        //     description: "",
        //     overallRating: '',
        //     personalRating: 'You have not rated this movie yet',
        //     genre: [],
        //     directors: [],
        //     staringActors: [],
        // },
        // {
        //     id: 51,
        //     title: '',
        //     releaseDate: '',
        //     cover: '',
        //     duration: '',
        //     description: "",
        //     overallRating: '',
        //     personalRating: 'You have not rated this movie yet',
        //     genre: [],
        //     directors: [],
        //     staringActors: [],
        // },
        // {
        //     id: 52,
        //     title: '',
        //     releaseDate: '',
        //     cover: '',
        //     duration: '',
        //     description: "",
        //     overallRating: '',
        //     personalRating: 'You have not rated this movie yet',
        //     genre: [],
        //     directors: [],
        //     staringActors: [],
        // },
        // {
        //     id: 53,
        //     title: '',
        //     releaseDate: '',
        //     cover: '',
        //     duration: '',
        //     description: "",
        //     overallRating: '',
        //     personalRating: 'You have not rated this movie yet',
        //     genre: [],
        //     directors: [],
        //     staringActors: [],
        // },
        // {
        //     id: 54,
        //     title: '',
        //     releaseDate: '',
        //     cover: '',
        //     duration: '',
        //     description: "",
        //     overallRating: '',
        //     personalRating: 'You have not rated this movie yet',
        //     genre: [],
        //     directors: [],
        //     staringActors: [],
        // },
        // {
        //     id: 55,
        //     title: '',
        //     releaseDate: '',
        //     cover: '',
        //     duration: '',
        //     description: "",
        //     overallRating: '',
        //     personalRating: 'You have not rated this movie yet',
        //     genre: [],
        //     directors: [],
        //     staringActors: [],
        // },
        // {
        //     id: 56,
        //     title: '',
        //     releaseDate: '',
        //     cover: '',
        //     duration: '',
        //     description: "",
        //     overallRating: '',
        //     personalRating: 'You have not rated this movie yet',
        //     genre: [],
        //     directors: [],
        //     staringActors: [],
        // },
        // {
        //     id: 57,
        //     title: '',
        //     releaseDate: '',
        //     cover: '',
        //     duration: '',
        //     description: "",
        //     overallRating: '',
        //     personalRating: 'You have not rated this movie yet',
        //     genre: [],
        //     directors: [],
        //     staringActors: [],
        // },
        // {
        //     id: 58,
        //     title: '',
        //     releaseDate: '',
        //     cover: '',
        //     duration: '',
        //     description: "",
        //     overallRating: '',
        //     personalRating: 'You have not rated this movie yet',
        //     genre: [],
        //     directors: [],
        //     staringActors: [],
        // },
        // {
        //     id: 59,
        //     title: '',
        //     releaseDate: '',
        //     cover: '',
        //     duration: '',
        //     description: "",
        //     overallRating: '',
        //     personalRating: 'You have not rated this movie yet',
        //     genre: [],
        //     directors: [],
        //     staringActors: [],
        // },
        // {
        //     id: 60,
        //     title: '',
        //     releaseDate: '',
        //     cover: '',
        //     duration: '',
        //     description: "",
        //     overallRating: '',
        //     personalRating: 'You have not rated this movie yet',
        //     genre: [],
        //     directors: [],
        //     staringActors: [],
        // },
        // {
        //     id: 61,
        //     title: '',
        //     releaseDate: '',
        //     cover: '',
        //     duration: '',
        //     description: "",
        //     overallRating: '',
        //     personalRating: 'You have not rated this movie yet',
        //     genre: [],
        //     directors: [],
        //     staringActors: [],
        // },

    ],
    
}